# Generated by Django 6.1 on 2026-09-15 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        ('voice', '0002_voiceroom_voiceroominvitationlink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voicesession',
            name='voice_session_shape_matches_kind',
        ),
        migrations.RemoveConstraint(
            model_name='voicesession',
            name='voice_direct_users_are_different',
        ),
        migrations.RemoveConstraint(
            model_name='voicesession',
            name='voice_group_session_not_ringing',
        ),
        migrations.AddField(
            model_name='voicesession',
            name='voice_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to='voice.voiceroom'),
        ),
        migrations.AlterField(
            model_name='voicesession',
            name='kind',
            field=models.CharField(choices=[('DIRECT', 'Direct call'), ('GROUP', 'Legacy group voice'), ('ROOM', 'Voice room')], max_length=6),
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['voice_room', 'status'], name='voice_session_room_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='voicesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('caller__isnull', False), ('group__isnull', True), ('kind', 'DIRECT'), ('recipient__isnull', False), ('ring_expires_at__isnull', False), ('voice_room__isnull', True)), models.Q(('caller__isnull', True), ('group__isnull', False), ('kind', 'GROUP'), ('recipient__isnull', True), ('ring_expires_at__isnull', True), ('voice_room__isnull', True)), models.Q(('caller__isnull', True), ('group__isnull', True), ('kind', 'ROOM'), ('recipient__isnull', True), ('ring_expires_at__isnull', True), ('voice_room__isnull', False)), _connector='OR'), name='voice_session_shape_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='voicesession',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['GROUP', 'ROOM']), models.Q(('caller', models.F('recipient')), _negated=True), _connector='OR'), name='voice_direct_users_are_different'),
        ),
        migrations.AddConstraint(
            model_name='voicesession',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['GROUP', 'ROOM']), ('status', 'RINGING'), _negated=True), name='voice_nondirect_session_not_ringing'),
        ),
        migrations.AddConstraint(
            model_name='voicesession',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'ROOM'), ('status', 'ACTIVE')), fields=('voice_room',), name='unique_active_voice_session_per_room'),
        ),
    ]
