# Generated by Django 6.1 on 2026-09-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_remove_voicesession_voice_session_shape_matches_kind_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voiceparticipation',
            name='unique_voice_participation_per_session_user',
        ),
    ]
