# Generated by Django 6.1 on 2026-09-10 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0002_alter_groupconversation_name_groupinvitationlink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direct_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.directconversation')),
                ('group_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.groupconversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['direct_conversation', 'created_at', 'id'], name='msg_dm_created_id_idx'), models.Index(fields=['group_conversation', 'created_at', 'id'], name='msg_group_created_id_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('direct_conversation__isnull', False), ('group_conversation__isnull', True)), models.Q(('direct_conversation__isnull', True), ('group_conversation__isnull', False)), _connector='OR'), name='message_has_exactly_one_context')],
            },
        ),
    ]
