"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os

from dotenv import load_dotenv

load_dotenv()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]

AUTH_USER_MODEL = "accounts.User"


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'channels',
    'rest_framework',
    'corsheaders',

    # Local
    'apps.accounts',
    'apps.friendships',
    'apps.conversations',
    'apps.messaging',
    'apps.attachments',
    'apps.realtime',
    'apps.activity',
    'apps.voice',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "config.api.authentication.SessionAuthentication401",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": (
        "rest_framework.pagination.PageNumberPagination"
    ),
    "PAGE_SIZE": 50,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                (
                    os.getenv("REDIS_HOST"),
                    int(os.getenv("REDIS_PORT", "6379")),
                )
            ],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

MESSAGE_ATTACHMENT_MAX_SIZE_BYTES = int(
    os.getenv('MESSAGE_ATTACHMENT_MAX_SIZE_BYTES', str(10 * 1024 * 1024))
)
MESSAGE_MAX_ATTACHMENTS = int(
    os.getenv('MESSAGE_MAX_ATTACHMENTS', '5')
)


# Voice / LiveKit
#
# Voice media is transported by LiveKit. Django remains authoritative for
# application authorization and only issues short-lived, scoped join tokens.
VOICE_ENABLED = os.getenv(
    "VOICE_ENABLED",
    "False",
).strip().lower() in {"1", "true", "yes", "on"}

LIVEKIT_URL = os.getenv(
    "LIVEKIT_URL",
    "",
).strip()
LIVEKIT_INTERNAL_URL = os.getenv(
    "LIVEKIT_INTERNAL_URL",
    "http://127.0.0.1:7880",
).strip()
LIVEKIT_API_KEY = os.getenv(
    "LIVEKIT_API_KEY",
    "",
).strip()
LIVEKIT_API_SECRET = os.getenv(
    "LIVEKIT_API_SECRET",
    "",
).strip()
VOICE_LIVEKIT_TOKEN_TTL_SECONDS = int(
    os.getenv(
        "VOICE_LIVEKIT_TOKEN_TTL_SECONDS",
        "60",
    )
)
VOICE_LIVEKIT_ADMIN_TIMEOUT_SECONDS = int(
    os.getenv(
        "VOICE_LIVEKIT_ADMIN_TIMEOUT_SECONDS",
        "2",
    )
)
VOICE_DIRECT_CALL_RING_TIMEOUT_SECONDS = int(
    os.getenv(
        "VOICE_DIRECT_CALL_RING_TIMEOUT_SECONDS",
        "45",
    )
)


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

LOGIN_URL = "auth-login"

# Base URL for links/redirects from Django-rendered account pages back to
# the React application. Production is served on the same origin, so the
# empty default produces paths such as "/messages". Development overrides
# this to point at the Vite dev server.
FRONTEND_BASE_URL = os.getenv(
    "DJANGO_FRONTEND_BASE_URL",
    "",
).rstrip("/")
