from django.urls import path

from apps.voice.api.v1.views import (
    DirectCallAcceptView,
    DirectCallCancelView,
    DirectCallEndView,
    DirectCallRejectView,
    DirectCallStartView,
    GroupVoiceLeaveView,
    GroupVoiceView,
    VoiceMediaCredentialsView,
    VoiceRoomDetailView,
    VoiceRoomIncomingInvitationListView,
    VoiceRoomInvitationAcceptView,
    VoiceRoomInvitationCancelView,
    VoiceRoomInvitationCollectionView,
    VoiceRoomInvitationLinkCollectionView,
    VoiceRoomInvitationLinkJoinView,
    VoiceRoomInvitationLinkRevokeView,
    VoiceRoomInvitationRejectView,
    VoiceRoomLeaveView,
    VoiceRoomListCreateView,
    VoiceRoomMemberDeleteView,
    VoiceRoomMemberListView,
    VoiceRoomVoiceLeaveView,
    VoiceRoomVoiceView,
    VoiceStateView,
)


urlpatterns = [
    path(
        "voice/rooms/",
        VoiceRoomListCreateView.as_view(),
        name="voice-room-list-create",
    ),
    path(
        "voice/rooms/<uuid:room_id>/invite-links/",
        VoiceRoomInvitationLinkCollectionView.as_view(),
        name="voice-room-invite-link-collection",
    ),
    path(
        "voice/rooms/<uuid:room_id>/invite-links/<uuid:link_id>/",
        VoiceRoomInvitationLinkRevokeView.as_view(),
        name="voice-room-invite-link-revoke",
    ),
    path(
        "voice/room-invite-links/join/",
        VoiceRoomInvitationLinkJoinView.as_view(),
        name="voice-room-invite-link-join",
    ),
    path(
        "voice/rooms/<uuid:room_id>/invitations/",
        VoiceRoomInvitationCollectionView.as_view(),
        name="voice-room-invitation-collection",
    ),
    path(
        "voice/rooms/<uuid:room_id>/invitations/<uuid:invitation_id>/",
        VoiceRoomInvitationCancelView.as_view(),
        name="voice-room-invitation-cancel",
    ),
    path(
        "voice/room-invitations/",
        VoiceRoomIncomingInvitationListView.as_view(),
        name="voice-room-incoming-invitation-list",
    ),
    path(
        "voice/room-invitations/<uuid:invitation_id>/accept/",
        VoiceRoomInvitationAcceptView.as_view(),
        name="voice-room-invitation-accept",
    ),
    path(
        "voice/room-invitations/<uuid:invitation_id>/reject/",
        VoiceRoomInvitationRejectView.as_view(),
        name="voice-room-invitation-reject",
    ),
    path(
        "voice/rooms/<uuid:room_id>/voice/",
        VoiceRoomVoiceView.as_view(),
        name="voice-room-voice",
    ),
    path(
        "voice/rooms/<uuid:room_id>/voice/leave/",
        VoiceRoomVoiceLeaveView.as_view(),
        name="voice-room-voice-leave",
    ),
    path(
        "voice/rooms/<uuid:room_id>/",
        VoiceRoomDetailView.as_view(),
        name="voice-room-detail",
    ),
    path(
        "voice/rooms/<uuid:room_id>/members/",
        VoiceRoomMemberListView.as_view(),
        name="voice-room-member-list",
    ),
    path(
        "voice/rooms/<uuid:room_id>/members/me/",
        VoiceRoomLeaveView.as_view(),
        name="voice-room-leave",
    ),
    path(
        "voice/rooms/<uuid:room_id>/members/<int:user_id>/",
        VoiceRoomMemberDeleteView.as_view(),
        name="voice-room-member-delete",
    ),
    path(
        "voice/state/",
        VoiceStateView.as_view(),
        name="voice-state",
    ),
    path(
        "voice/direct-calls/",
        DirectCallStartView.as_view(),
        name="voice-direct-call-start",
    ),
    path(
        "voice/direct-calls/<uuid:session_id>/accept/",
        DirectCallAcceptView.as_view(),
        name="voice-direct-call-accept",
    ),
    path(
        "voice/direct-calls/<uuid:session_id>/reject/",
        DirectCallRejectView.as_view(),
        name="voice-direct-call-reject",
    ),
    path(
        "voice/direct-calls/<uuid:session_id>/cancel/",
        DirectCallCancelView.as_view(),
        name="voice-direct-call-cancel",
    ),
    path(
        "voice/direct-calls/<uuid:session_id>/end/",
        DirectCallEndView.as_view(),
        name="voice-direct-call-end",
    ),
    path(
        "voice/sessions/<uuid:session_id>/media-credentials/",
        VoiceMediaCredentialsView.as_view(),
        name="voice-media-credentials",
    ),
    path(
        "groups/<int:group_id>/voice/",
        GroupVoiceView.as_view(),
        name="group-voice",
    ),
    path(
        "groups/<int:group_id>/voice/leave/",
        GroupVoiceLeaveView.as_view(),
        name="group-voice-leave",
    ),
]
